version: 2
updates:
- package-ecosystem: npm
  directory: "/4-vue-cli/vueapp"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: npm
  directory: "/5-nette"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: composer
  directory: "/5-nette"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
