version: 2
updates:
- package-ecosystem: npm
  directory: "/4-vue-cli/vueapp"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/5-nette"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/5-nette"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10